# Generated by Django 5.0.4 on 2024-05-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginDjango', '0003_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_upload',
            field=models.FileField(blank=True, null=True, upload_to='imagens_produtos'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
