# Generated by Django 5.0.4 on 2024-05-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginDjango', '0005_alter_produto_imagem_upload_alter_produto_imagem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='descricao_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem_upload',
            new_name='imagem_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_produto',
        ),
    ]
