# Generated by Django 5.0.4 on 2024-05-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginDjango', '0006_rename_descricao_produto_descricao_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem_url',
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagem_produto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginDjango.produto')),
            ],
        ),
    ]
